---
title: "graphs"
output: html_document
date: "2022-11-22"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(plotly)
library(countrycode)
library(hrbrthemes)
```

```{r message=FALSE, warning=FALSE}
#setwd("C:/Users/Anna/Desktop/Hertie/second_year/GHG-project")
owid <- read_csv("data/owid-co2-data.csv")
```

```{r}
owid <-owid%>%mutate(gdp_per_capita=gdp/population)
owid<-owid%>%filter(!country %in% c("International transport", "Kuwaiti Oil Fires"))
owid<-owid%>%mutate(continent = countrycode(iso_code, origin = "iso3c", destination = "continent"))
```

```{r}
figure_1 <- owid %>% 
  filter(!is.na(consumption_co2))%>% filter(country %in% c("World", "Africa", "North America", "Europe (excl. EU-28)", "South America", "Asia", "Australia", "Asia (excl. China & India)", "European Union (28)", "North America (excl. USA)", "Oceania", "Antarctica"))%>%
  filter(year==2018) %>% 
  arrange(desc(consumption_co2)) %>% 
  ggplot(.,aes(x=consumption_co2,y=reorder(country,consumption_co2))) +
  geom_col(color="#636363",fill="#BD1550") +
  scale_fill_brewer(palette="Set2") +
  theme_bw() +
  theme(axis.title.y = element_blank()) +
  xlab("") +
  ggtitle("Consumption of CO2 per Region in 2018")+guides(fill=guide_legend(title=" "))

ggsave("pics/Fig. 1 Consumption by Region 2018", plot = figure_1, device = "png", width = 10, height = 8)
```

```{r}
figure_2 <- owid %>% filter(!is.na(co2))%>% filter(country %in% c("World", "Africa", "North America", "Europe (excl. EU-28)", "South America", "Asia", "Australia", "Asia (excl. China & India)", "European Union (28)", "North America (excl. USA)", "Oceania", "Antarctica"))%>%
  filter(year==2018) %>% 
  arrange(desc(co2)) %>% 
  ggplot(.,aes(x=co2,y=reorder(country,co2))) +
  geom_col(color="#636363",fill="#490A3D") +
  theme_bw() +
  theme(axis.title.y = element_blank()) +
  xlab("") +
  ggtitle("Production of CO2 per Region in 2018")+guides(fill=guide_legend(title=" "))

ggsave("pics/Fig. 2 Production by Region 2018", plot = figure_2, device = "png", width = 10, height = 8)
```

```{r message=FALSE, warning=FALSE}
figure_3 <- owid %>% 
  filter(country %in% c("Africa", "North America", "Europe", "South America", "Asia", "Australia", "Asia (excl. China & India)", "North America (excl. USA)", "Oceania", "Antarctica")) %>% filter(year>=1990 & year<=2018) %>%
  ggplot(.,aes(x=year,y=consumption_co2,fill=country)) +
  geom_area(color="#636363", position="fill") +
  theme_bw() +
  scale_fill_brewer(palette="RdPu") +
  ylab("") +
  theme(axis.title.x=element_blank()) +
  ggtitle(paste0("Share of CO2 Consumption across Regions since 1990"))+guides(fill=guide_legend(title=" "))

ggsave("pics/Fig. 3 share of consumption by region s1990", plot = figure_3, device = "png", width = 10, height = 8)
```

```{r}
figure_4 <- owid %>% filter(year>=1990 & year<=2018) %>%
  filter(country %in% c("Africa", "North America", "Europe", "South America", "Asia", "Australia", "Asia (excl. China & India)", "North America (excl. USA)", "Oceania", "Antarctica")) %>% 
  ggplot(.,aes(x=year,y=co2,fill=country)) +
  geom_area(color="#636363", position="fill") +
  theme_bw() +
  scale_fill_brewer(palette="BuPu") +
  ylab("") +
  theme(axis.title.x=element_blank()) +
  ggtitle(paste0("Share of CO2 Production across Regions since 1990"))+guides(fill=guide_legend(title=" "))

ggsave("pics/Fig. 4 share of production by region s1990", plot = figure_4, device = "png", width = 10, height = 8)
```

```{r message=FALSE, warning=FALSE}
figure_1
figure_2
figure_3
figure_4
```


```{r}
figure_5 <- owid %>% filter(!is.na(consumption_co2))%>% filter(!country %in% c("World", "Africa", "North America", "Europe (excl. EU-28)", "South America", "Asia", "Australia", "Asia (excl. China & India)", "European Union (28)", "Europe","Europe (excl. EU-27)", "European Union (27)", "High-income countries", "Upper-middle-income countries", "Lower-middle-income countries", "North America (excl. USA)","Oceania", "Antarctica"))%>%
  filter(year==2018) %>% 
  arrange(desc(consumption_co2)) %>% 
  head(10) %>% 
  ggplot(.,aes(x=consumption_co2,y=reorder(country,consumption_co2))) +
  geom_col(color="#636363",fill="#BD1550") +
  scale_fill_brewer(palette="Set2") +
  theme_bw() +
  theme(axis.title.y = element_blank()) +
  xlab("") +
  ggtitle("Consumption of CO2 per country in 2018")

ggsave("pics/Fig. 5 consumption by country 2018", plot = figure_5, device = "png", width = 10, height = 8)
```

```{r}
figure_6 <- owid %>% filter(!is.na(co2)) %>% 
  filter(!country %in% c("World", "Africa", "North America", "Europe (excl. EU-28)", "South America", "Asia", "Australia", "Asia (excl. China & India)", "European Union (28)", "Europe","Europe (excl. EU-27)", "European Union (27)", "High-income countries", "Upper-middle-income countries", "Lower-middle-income countries", "North America (excl. USA)",  "Oceania", "Antarctica")) %>%
  filter(year==2018) %>% 
  arrange(desc(co2)) %>% 
  head(10) %>% 
  ggplot(.,aes(x=co2,y=reorder(country,co2))) +
  geom_col(color="#636363",fill="#490A3D") +
  theme_bw() +
  theme(axis.title.y = element_blank()) +
  xlab("") +
  ggtitle("Production of CO2 per country in 2018")

ggsave("pics/Fig. 6 production by country 2018", plot = figure_6, device = "png", width = 10, height = 8)
```

```{r}
figure_5
figure_6
```

```{r message=FALSE, warning=FALSE}
figure_7 <- owid %>% filter(year>=1990 & year<=2018) %>%
  filter(country %in% c( "High-income countries", "Upper-middle-income countries", "Lower-middle-income countries", "Low-income countries")) %>% 
  ggplot(.,aes(x=year,y=consumption_co2,fill=country)) +
  geom_area(color="#636363", position="fill") +
  theme_bw() +
  scale_fill_brewer(palette="RdPu") +
  ylab("") +
  theme(axis.title.x=element_blank()) +
  ggtitle(paste0("Share of consumption based CO2 emissions by income  1990-2018"))+guides(fill=guide_legend(title=" "))

ggsave("pics/Fig. 7 consumption by income s1990", plot = figure_7, device = "png", width = 10, height = 8)

figure_8 <- owid %>% filter(year>=1990 & year<=2018) %>%
  filter(country %in% c("High-income countries", "Upper-middle-income countries", "Lower-middle-income countries", "Low-income countries")) %>% 
  ggplot(.,aes(x=year,y=co2,fill=country)) +
  geom_area(color="#636363", position="fill") +
  theme_bw() +
  scale_fill_brewer(palette="BuPu") +
  ylab("") +
  theme(axis.title.x=element_blank()) +
  ggtitle(paste0("Share of CO2 production based CO2 emissions by income 1990-2018"))+guides(fill=guide_legend(title=" "))

ggsave("pics/Fig. 8 production by income s1990", plot = figure_8, device = "png", width = 10, height = 8)
```

```{r message=FALSE, warning=FALSE}
figure_7
figure_8
```

```{r}
figure_9 <- owid%>% filter(!is.na(country))%>% filter(!country %in% c("World", "Africa", "North America", "Europe (excl. EU-28)", "South America", "Asia","Asia (excl. China & India)", "European Union (28)", "Europe","Europe (excl. EU-27)", "European Union (27)", "High-income countries", "Upper-middle-income countries", "Lower-middle-income countries", "North America (excl. USA)", "Oceania", "Antarctica")) %>%filter(year==2018) %>%  filter(!is.na(gdp_per_capita)&!is.na(co2)&!is.na(consumption_co2))%>%arrange(desc(gdp_per_capita)) %>% 
  head(12) %>% plot_ly( x = ~co2, y = ~consumption_co2, type = 'scatter', mode = 'markers', size = ~gdp_per_capita, color = ~country, colors = 'Paired',
        sizes = c(50, 1000))

figure_9 <- figure_9 %>%
  layout(title = 'Consumption vs production based emissions (top 12 by GDP per capita)',
         xaxis = list(title = 'Production of CO2 in million tonnes'), 
         yaxis = list(title = 'Consumption of CO2 in million tonnes'))%>%  
  layout(showlegend = FALSE)

htmlwidgets::saveWidget(figure_9, file = "pics/figure_9.html")
figure_9
```

```{r message=FALSE, warning=FALSE}
figure_10 <- owid%>% filter(!is.na(country))%>% filter(!country %in% c("World", "Africa", "North America", "Europe (excl. EU-28)", "South America", "Asia","Asia (excl. China & India)", "European Union (28)", "Europe","Europe (excl. EU-27)", "European Union (27)", "High-income countries", "Upper-middle-income countries", "Lower-middle-income countries", "North America (excl. USA)", "Oceania", "Antarctica"))%>%
  filter(year==2018) %>%
  filter(!is.na(gdp_per_capita)&!is.na(co2)&!is.na(consumption_co2)) %>%
  arrange(desc(gdp_per_capita)) %>% 
  slice_min(gdp_per_capita,n=12) %>% 
  plot_ly( x = ~co2, y = ~consumption_co2, type = 'scatter', mode = 'markers', size = ~gdp_per_capita, color = ~country, colors = 'Paired',
        sizes = c(50, 1000))

figure_10  <- figure_10  %>%
  layout(title = 'Consumption vs production based emissions (bottom 12 by GDP per capita)',
         xaxis = list(title = 'Production of CO2 in million tonnes'), yaxis = list(title = 'Consumption of CO2 in million tonnes'))
figure_10
htmlwidgets::saveWidget(figure_10, file = "pics/figure_10.html")
```

```{r}
figure_11 <- owid %>% filter(!is.na(co2)) %>% 
  filter(!country %in% c("World", "Africa", "North America", "Europe (excl. EU-28)", "South America", "Asia", "Australia", "Asia (excl. China & India)", "European Union (28)", "Europe","Europe (excl. EU-27)", "European Union (27)", "High-income countries", "Upper-middle-income countries", "Lower-middle-income countries", "North America (excl. USA)",  "Oceania", "Antarctica")) %>%
  filter(year==2018) %>% 
  arrange(desc(co2_per_gdp)) %>% 
  head(10) %>% 
  ggplot(.,aes(x=co2_per_gdp,y=reorder(country,co2_per_gdp))) +
  geom_col(color="#636363",fill="#490A3D") +
  theme_bw() +
  theme(axis.title.y = element_blank()) +
  xlab("") +
  ggtitle("Production of CO2 per gdp in 2018")

ggsave("pics/Fig. 11", plot = figure_11, device = "jpg", width = 10, height = 8)
```

```{r}
figure12<-df_consumption_gdp%>%select(emiss_18, gdp_18, country)%>%mutate(emiss_per_gdp=emiss_18/gdp_18)%>%
  arrange(desc(emiss_per_gdp)) %>% 
  head(10) %>% 
  ggplot(.,aes(x=emiss_per_gdp,y=reorder(country,emiss_per_gdp))) +
  geom_col(color="#636363",fill="#BD1550") +
  theme_bw() +
  theme(axis.title.y = element_blank()) +
  xlab("") +
  ggtitle("Consumption of CO2 per gdp in 2018")
ggsave("pics/Fig. 12", plot = figure_12, device = "jpg", width = 10, height = 8)
```

```{r}
df = owid

#annual production plot

co2_prdo_annual = df$co2[df$country == 'World']
date = df$year[df$country == 'World']
df_2 = data.frame(cbind(date,co2_prdo_annual))
year = df_2$date[df_2$date >= 1990 & df_2$date <= 2018]
co2_production = df_2$co2_prdo_annual[df_2$date >= 1990 & df_2$date <= 2018]
df_def = data.frame(cbind(year,co2_production))

figure_13<-df_def %>%
  tail(29) %>%
  ggplot( aes(x=year, y=co2_production)) +
  geom_line( color="lightblue") +
  geom_point(shape=21, color="black", fill="lightblue", size=2)+
  xlab('Year')+
  ylab('Million tonnes of  CO2 production')+
  ggtitle("Overall trend of production-based CO2 emissions") + theme_minimal()

figure_13
ggsave("pics/Fig. 13", plot = figure_13, device = "jpg", width = 10, height = 8)
```

```{r}
#annual consumption plot

co2_cons = df$consumption_co2[df$country == 'World']
df_cons = data.frame(cbind(date,co2_cons))
co2_consumption = df_cons$co2_cons[df_cons$date >= 1990 & df_cons$date <= 2018]
df_def_cons = data.frame(cbind(year,co2_consumption))


figure_14<-df_def_cons %>%
  tail(29) %>%
  ggplot( aes(x=year, y=co2_consumption)) +
  geom_line( color="pink") +
  geom_point(shape=21, color="black", fill="pink", size=2) +
  xlab('Year')+
  ylab('Million tonnes of  CO2 consumption')+
  ggtitle("Overall trend of consumption-based CO2 emissions") + theme_minimal()

figure_14
ggsave("pics/Fig. 14", plot = figure_14, device = "jpg", width = 10, height = 8)
```

```{r}
#US
co2_prdo_annual_US = df$co2[df$country == 'United States']

date = df$year[df$country == 'United States']
df_2_US = data.frame(cbind(date,co2_prdo_annual_US))
year_US = df_2_US$date[df_2_US$date >= 1990 & df_2_US$date <= 2018]
co2_production_US = df_2_US$co2_prdo_annual_US[df_2_US$date >= 1990 & df_2_US$date <= 2018]



co2_cons_US = df$consumption_co2[df$country == 'United States']
df_cons_US = data.frame(cbind(date,co2_cons_US))
co2_consumption_US = df_cons_US$co2_cons_US[df_cons_US$date >= 1990 & df_cons_US$date <= 2018]
df_def_cons_US = data.frame(cbind(year,co2_consumption_US))


# Make a basic graph
plot(co2_consumption_US ~ year, type="b" , bty="l" , xlab="Year" , ylab="CO2 emissions (Million Tonnes)" , col='lightblue' , lwd=2 , pch=17, main = 'CO2 emissions in the US per year')
lines(co2_production_US ~ year, col='pink' , lwd=2 , pch=19 , type="b" )

# Add a legend
legend("topleft", 
       legend = c("Overall trend of consumption-based CO2 emissions in the US", "Overall trend of production-based CO2 emissions in the US"), 
       col = c('lightblue', 
               'pink'), 
       pch = c(17,19), 
       bty = "n", 
       pt.cex = 1, 
       cex = 1, 
       text.col = "black", 
       horiz = F , 
       inset = c(0.01, 0.01))

```


```{r}
#consumption/production

cons_prod_US = co2_consumption_US/co2_production_US
cons_prod_US_df = data.frame(cbind(year,cons_prod_US))

cons_prod_US_df %>%
  tail(29) %>%
  ggplot( aes(x=year, y=cons_prod_US)) +
  geom_line( color="orchid") +
  geom_point(shape=21, color="black", fill="orchid", size=2) +
  xlab('Year')+
  ylab('Relative change in CO2 emissions (Mt)')+
  ggtitle("CO2 emission changes according to CBA/PBA ratio in the US") + theme_minimal()

```

```{r}
#China
co2_prdo_annual_China = df$co2[df$country == 'China']
date = df$year[df$country == 'China']
df_2_China = data.frame(cbind(date,co2_prdo_annual_China))
year_China = df_2_China$date[df_2_China$date >= 1990 & df_2_China$date <= 2018]
co2_production_China = df_2_China$co2_prdo_annual_China[df_2_China$date >= 1990 & df_2_China$date <= 2018]
co2_cons_China = df$consumption_co2[df$country == 'China']
df_cons_China = data.frame(cbind(date,co2_cons_China))
co2_consumption_China = df_cons_China$co2_cons_China[df_cons_China$date >= 1990 & df_cons_China$date <= 2018]
df_def_cons_China = data.frame(cbind(year,co2_consumption_China))




# Make a basic graph
plot(co2_consumption_China ~ year, type="b" , bty="l" , xlab="Year" , ylab="CO2 emissions (Million Tonnes)" , col='lightblue' , lwd=2 , pch=17,ylim = c(2200,10500), main = 'CO2 emissions in China per year')
lines(co2_production_China ~ year, col='pink' , lwd=2 , pch=19 , type="b" )

# Add a legend
legend("topleft", 
       legend = c("Overall trend of consumption-based CO2 emissions in China", "Overall trend of production-based CO2 emissions in China"), 
       col = c('lightblue', 
               'pink'), 
       pch = c(17,19), 
       bty = "n", 
       pt.cex = 1, 
       cex = 1, 
       text.col = "black", 
       horiz = F , 
       inset = c(0.01, 0.01))


```

```{r}
#consumption/production

cons_prod_China = co2_consumption_China/co2_production_China

cons_prod_China_df = data.frame(cbind(year,cons_prod_China))
cons_prod_China_df %>%
  tail(29) %>%
  ggplot( aes(x=year, y=cons_prod_China)) +
  geom_line( color="orchid") +
  geom_point(shape=21, color="black", fill="orchid", size=2) +
  xlab('Year')+
  ylab('Relative change in CO2 emissions (Mt)')+
  ggtitle("CO2 emission changes according to CBA/PBA ratio in China") + theme_minimal()
```

