---
title: "GHG Presentation"
author: "Maren Rieker, Ania Matysiak, Laura Menicacci"
date: "2022-11-19"
output:
  xaringan::moon_reader:
    css: [default,'simons-touch.css', metropolis, metropolis-fonts] 
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      ratio: '16:9'
      hash: true
---
```{r, include=FALSE}
library(tidyverse)
library(plotly)
library(shiny)
```

```{r, include=FALSE}
owid <- read_csv("owid-co2-data.csv")

owid %>% 
  rename(co2_miot = co2) %>%  #make clear that total co2 emissions are measured in million tonnes
  rename(consumption_co2_miot = consumption_co2) #same for consumption-based emissions
  
owids <- owid %>% 
  group_by(country) %>% 
  mutate(cumulatives_co2 = sum(cumulative_co2)) %>% 
  drop_na()

owids %>%  
  head()

owids %>% colnames()
```

Play with the plots
```{r}
plot <- owid %>% 
  drop_na() %>% 
  filter(year == 2018) %>% 
  mutate(pop = population/1000000, 2) %>% 
  ggplot(aes(x = co2, y = consumption_co2, size = population, colour = country)) +
  geom_point()
```

## Slide with Bullets

- Bullet 1
- Bullet 2
- Bullet 3

SHINY SHIT
```{r}
ui <- fluidPage(
  titlePanel("Production based vs. Consumption based CO2 Emissions"),
  
  sidebarLayout(
    sidebarPanel(
      sliderInput(inputId = owid$year,
                  label = "Year",
                  min = 1990,
                  max = 2018,
                  value = 2018)
    ),
  mainPanel(
    plotOutput(outputId = "plot")
    )
  )
)

server <- function(input, output) {
  output$plot <- renderPlot({
    data <- switch(input$var,
                   "Consumption-based" = owid$consumption_co2,
                   "Production-based" = owid$co2,
                   "Population" = pop)
  })
  
}


# Create Shiny app ----
shinyApp(ui = ui, server = server)
```

