---
title: "GHG Project"
author: "Maren Rieker, Ania Matysiak, Laura Menicacci"
date: "2022-11-19"
output: html_document
---

```{r, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      eval = TRUE,
                      error = FALSE,
                      message = FALSE,
                      warning = FALSE,
                      comment = NA)
```

This is the code for our final Project for the class *Data Perspectives on Greenhouse Gas Emissions*, taught by Will Lamb and Michael Jakob.

#Outline
1. 


Libraries used
```{r, include = TRUE}
library(tidyverse)
library(gridExtra)
library(grid)
library(showtext)
library(RColorBrewer)
library(ggrepel)
library(ggplotlyExtra)
```

# 1. Load and initialise necessary dataset
```{r}
owid <- read_csv("owid-co2-data.csv")

owid %>% 
  rename(co2_miot = co2) %>%  #make clear that total co2 emissions are measured in million tonnes
  rename(consumption_co2_miot = consumption_co2) #same for consumption-based emissions
  
owids <- owid %>% 
  group_by(country) %>% 
  mutate(cumulatives_co2 = sum(cumulative_co2))

owids %>%  
  head()

owids %>% colnames()
```

Play with the plots
```{r}
owid %>% 
  drop_na() %>%
  filter(year == 1995) %>% 
  mutate(pop = round(population/1000000, 2)) %>% # round pop by million
  ggplot(aes(x = co2, y = consumption_co2, size = pop, colour = country)) +
  geom_point()+ theme_bw()
```


